### ISSUE TITLE
ui-icon does not automatically install ember-cli-stylist dependency

### ISSUE THREAD

**Issue by pauldoerwald** [lifegadget/ui-icon#6]
I've been trying to get ui-icon to work, but it's been failing. I eventually discovered that I need to manually install ember-cli-stylist to get it to work. I'm afraid I don't know enough about add-ons to provide a pull request, but the problem is easy enough to reproduce:
1. `ember new foo && cd foo`
2. `ember install ui-icon`
3. edit `application.hbs` and add `{{ui-icon 'twitter-square'}}` somewhere
4. run ember and look at the page. It'll be blank.
5. `ember install ember-cli-stylist` and restart the server
6. take another look at the page, and the fontawesome icon will appear as expected.

This problem occurs in Ember 2.4.3 and 2.5.0.

**Comment by yankeeinlondon** [comment]
Thanks. Can't believe I didn't run into that myself. In any event. Should be fixed now in `0.10.1`. Have a look and let me know if that works.

**Comment by pauldoerwald** [comment]
Confirmed! I removed ember-cli-stylist from my package.json, restarted ember and confirmed the problem existed. Then I changed the version for ui-icon to 0.10.1 in package.json, npm install, and restarted ember, and everything worked as expected. Thanks!

**Comment by yankeeinlondon** [comment]
Great, thanks Paul.
